#spring:
#  datasource:
#    username: clyummmy
#    password: Iknowyoulikeit;)
#    url: jdbc:mysql://localhost:3306/gmj_yummmy
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect